// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDul3MPgrjVAu0RnSpxq-rpaHX0cljx8so',
    appId: '1:98717961407:web:0dd0d3317444e4e96aca0a',
    messagingSenderId: '98717961407',
    projectId: 'flutter-choice-app',
    authDomain: 'flutter-choice-app.firebaseapp.com',
    storageBucket: 'flutter-choice-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmejyYSj9zikhZFJYfHf13B593Ey251w8',
    appId: '1:98717961407:android:38c3f7ac0949a5a96aca0a',
    messagingSenderId: '98717961407',
    projectId: 'flutter-choice-app',
    storageBucket: 'flutter-choice-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbm2k_uPO3OHFu37F3uPxkmZGP3eop40I',
    appId: '1:98717961407:ios:06c4c6bf0ce06e4c6aca0a',
    messagingSenderId: '98717961407',
    projectId: 'flutter-choice-app',
    storageBucket: 'flutter-choice-app.appspot.com',
    iosBundleId: 'com.example.noNameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbm2k_uPO3OHFu37F3uPxkmZGP3eop40I',
    appId: '1:98717961407:ios:e59a1adaa656f9566aca0a',
    messagingSenderId: '98717961407',
    projectId: 'flutter-choice-app',
    storageBucket: 'flutter-choice-app.appspot.com',
    iosBundleId: 'com.example.noNameApp.RunnerTests',
  );
}
